# Generated by Django 4.2.5 on 2024-07-15 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('text', models.TextField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'activity_news',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'เงินสด'), ('transfer', 'เงินโอน')], max_length=10)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_text', models.CharField(max_length=255)),
                ('receiver_name', models.CharField(choices=[('นายนิพนธ์ โพธิ์ชัย', 'นายนิพนธ์ โพธิ์ชัย'), ('นายบุญชู ภาคพิม', 'นายบุญชู ภาคพิม'), ('นางศิริกุล ชำนาณเวช', 'นางศิริกุล ชำนาณเวช')], max_length=255)),
                ('transfer_receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Donation',
            },
        ),
        migrations.CreateModel(
            name='Income_expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('income', models.TextField()),
                ('expenses', models.TextField()),
                ('image', models.ImageField(upload_to='Income_expenses_images/')),
            ],
            options={
                'db_table': 'income_expenses',
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Representative_images/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'representative',
            },
        ),
        migrations.CreateModel(
            name='Villagepublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Villagepublic_images/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'villagepublic',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_message', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('road', 'เรื่องถนน'), ('water', 'เรื่องน้ำ'), ('electricity', 'เรื่องไฟฟ้า'), ('general', 'เรื่องทั่วไป')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
    ]
