# Generated by Django 4.2.5 on 2024-07-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitsa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='receiver_name',
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'เงินโอน')], max_length=10),
        ),
    ]
