# Generated by Django 4.2.5 on 2024-07-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitsa', '0002_remove_donation_receiver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
