# Generated by Django 4.2.5 on 2024-07-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitsa', '0003_donation_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_expenses',
            name='expenses_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='income_expenses',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
